import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { loadGameSource } from "./game-test-helpers.mjs";

const path = "app/games/_components/pokemon-marble/";
const { parseGameSave, validateSave } = loadGameSource(`${path}save.ts`);
const { validateV2Save } = loadGameSource(`${path}save-v2.ts`);
const { createGame, transition, getStats } = loadGameSource(`${path}engine.ts`);
// Golden states generated by the pre-patch v2 engine, including pending rewards.
const fixtures = JSON.parse(readFileSync(new URL("./fixtures/pokemon-v2.json", import.meta.url), "utf8"));

function allPokemon(state) {
  return [
    ...state.players.flatMap((player) => [...player.party, ...player.box]),
    ...state.roads.flatMap((guardian) => guardian ? [guardian.pokemon] : []),
    ...(state.battle?.wild ? [state.battle.wild] : []),
  ];
}

test("v2 golden states migrate without changing progress, identities, HP or RNG", () => {
  for (const [name, legacy] of Object.entries(fixtures)) {
    const original = structuredClone(legacy);
    assert.ok(validateV2Save(legacy), name);
    const migrated = parseGameSave(legacy);
    assert.ok(validateSave(migrated), name);
    assert.equal(migrated.version, 4);
    for (const field of ["revision", "rng", "nextPokemonId", "turn", "phase"])
      assert.equal(migrated[field], legacy[field], `${name}: ${field}`);
    assert.deepEqual(allPokemon(migrated).map(({ xp, ...pokemon }) => {
      assert.equal(xp, 0);
      return pokemon;
    }), allPokemon(legacy));
    assert.deepEqual(legacy, original, "Reading a save must not modify it");
    assert.deepEqual(parseGameSave(migrated), migrated);
  }
});

test("legacy capture and wild evolution finish once without new experience", () => {
  for (const fixture of [fixtures.capture, fixtures.wildEvolution]) {
    let state = parseGameSave(fixture);
    if (state.phase === "evolution")
      state = transition(state, { type: "CHOOSE_EVOLUTION", speciesId: 134 });
    assert.equal(state.phase, "capture");
    assert.equal(state.players[0].party[0].level, 20);
    assert.equal(state.players[0].party[0].xp, 0);
    assert.ok(validateSave(state));
    const capturedId = state.battle.wild.id;
    const next = transition(parseGameSave(state), { type: "CAPTURE", capture: true });
    assert.equal(next.players[0].party.find((pokemon) => pokemon.id === capturedId).hp, 0);
    assert.equal(next.players[0].party[0].xp, 0);
    assert.equal(transition(next, { type: "CAPTURE", capture: true }), next);
    assert.ok(validateSave(next));
  }
});

test("legacy trainer, road and lap evolution never re-award growth", () => {
  for (const fixture of [fixtures.trainerEvolution, fixtures.roadEvolution, fixtures.lapEvolution]) {
    let state = parseGameSave(fixture);
    const expected = new Map(allPokemon(state).map((pokemon) => [pokemon.id, pokemon.level]));
    let count = 0;
    while (state.phase === "evolution") {
      assert.ok(count++ < 5);
      state = transition(parseGameSave(state), { type: "CHOOSE_EVOLUTION", speciesId: state.evolution.options[0] });
      assert.ok(validateSave(state));
    }
    for (const pokemon of allPokemon(state)) {
      assert.equal(pokemon.level, expected.get(pokemon.id));
      assert.equal(pokemon.xp, 0);
    }
    if (fixture === fixtures.lapEvolution) {
      assert.equal(state.roads[2].pokemon.speciesId, 133);
      assert.equal(state.roads[2].pokemon.level, 19);
      assert.equal(state.phase, "moving");
    }
  }
});

test("legacy full-party capture can be declined and older saves can omit lap growth", () => {
  const legacy = structuredClone(fixtures.capture);
  while (legacy.players[0].party.length < 6)
    legacy.players[0].party.push({ ...legacy.players[1].party[0], id: `p${legacy.nextPokemonId++}` });
  const pending = parseGameSave(legacy);
  assert.ok(pending);
  assert.equal(transition(pending, { type: "CAPTURE", capture: true }), pending);
  const declined = transition(pending, { type: "CAPTURE", capture: false });
  assert.equal(declined.phase, "turn-end");
  assert.equal(declined.players[0].party.length, 6);
  assert.ok(validateSave(declined));
  const earlier = structuredClone(fixtures.roll);
  delete earlier.lapGrowth;
  assert.ok(validateSave(parseGameSave(earlier)));
});

test("load migration is read-only and the next accepted action uses version 4", () => {
  const envelope = { protocol: "nemonori.save.v1", gameSlug: "pokemon-marble", gameTitle: "포켓몬 마블", updatedAt: "2026-10-03T00:00:00.000Z", data: fixtures.roll };
  const original = structuredClone(envelope);
  const { loadPokemonSave } = loadGameSource(`${path}load-save.ts`, {
    "app/lib/save-protocol.ts": { loadGameSave: () => ({ ok: true, value: envelope }) },
  });
  const result = loadPokemonSave();
  assert.ok(result.ok);
  assert.deepEqual(envelope, original);
  assert.equal(transition(result.value.data, { type: "ROLL" }).version, 4);
});

test("invalid v2 and malformed v3 experience/outcomes are rejected", () => {
  const old = structuredClone(fixtures.capture);
  old.battle.wild.hp = 1;
  assert.equal(parseGameSave(old), null);
  for (const xp of [undefined, -1, 1000, 1.5, NaN, Infinity]) {
    const state = createGame([1], [], 1);
    state.players[0].party[0].xp = xp;
    assert.equal(validateSave(state), false);
  }
  const max = createGame([1], [], 1);
  max.players[0].party[0].level = 100;
  max.players[0].party[0].xp = 1;
  assert.equal(validateSave(max), false);
  for (const outcome of [undefined, {}, { kind: "capture" }, { kind: "knockout", winner: "other" }]) {
    const state = parseGameSave(fixtures.evolvedWild);
    state.battle.outcome = outcome;
    assert.equal(validateSave(state), false);
  }
});

test("successful capture can resume branching evolution with one reward and one party transfer", () => {
  let state = parseGameSave(fixtures.evolvedWild);
  const attacker = state.players[0].party[0];
  attacker.speciesId = 133;
  attacker.level = 19;
  attacker.xp = 900;
  attacker.hp = getStats(attacker).hp;
  state = transition(state, { type: "CHOOSE_POKEMON", pokemonId: attacker.id });
  state = transition(state, { type: "WILD_ATTACK" });
  state.battle.wild.hp = 1;
  state.rng = 1;
  const capturedId = state.battle.wild.id;
  state = transition(state, { type: "THROW_BALL" });
  assert.equal(state.phase, "evolution");
  assert.deepEqual(state.battle.outcome, { kind: "capture" });
  assert.equal(state.players[0].party.length, 1);
  assert.ok(validateSave(state));
  const rewarded = { level: state.players[0].party[0].level, xp: state.players[0].party[0].xp };
  const next = transition(parseGameSave(state), { type: "CHOOSE_EVOLUTION", speciesId: 134 });
  assert.equal(next.phase, "turn-end");
  assert.equal(next.players[0].party.length, 2);
  assert.equal(next.players[0].party[1].id, capturedId);
  assert.equal(next.players[0].party[1].hp, 1);
  assert.equal(next.players[0].party[0].level, rewarded.level);
  assert.equal(next.players[0].party[0].xp, rewarded.xp);
  assert.ok(validateSave(next));
  assert.equal(transition(next, { type: "THROW_BALL" }), next);
});
